export enum EvidenceRoutes {
  EVIDENCE = "/evidence",
  EVIDENCE_CONCEPTS = "/evidence/concepts",
  EVIDENCE_DOCUMENTS = "/evidence/documents",
  EVIDENCE_DOCUMENTS_FORPROCESSING = "/evidence/documents/for-processing",
  EVIDENCE_DOCUMENTS_PROCESSED = "/evidence/documents/processed",
  EVIDENCE_FILES = "/evidence/files",
  EVIDENCE_FILES_CLOSED = "/evidence/files/closed",
  EVIDENCE_FILES_OPEN = "/evidence/files/open",
  EVIDENCE_OVERVIEWS = "/evidence/overviews",
  EVIDENCE_OVERVIEWS_FORSIGNATURE = "/evidence/overviews/for-signature",
  EVIDENCE_OVERVIEWS_LOSTDESTROYED = "/evidence/overviews/lost-destroyed",
  EVIDENCE_OVERVIEWS_REJECTEDBYTAKEOVER = "/evidence/overviews/rejected-by-takeover",
  EVIDENCE_OVERVIEWS_RENTED = "/evidence/overviews/rented",
  EVIDENCE_OVERVIEWS_RETURNEDFORREWORK = "/evidence/overviews/returned-for-rework",
  EVIDENCE_OVERVIEWS_RETURNEDFROMDISPATCH = "/evidence/overviews/returned-from-dispatch",
  EVIDENCE_OVERVIEWS_CANCEL = "/evidence/overviews/cancel",
  EVIDENCE_TOTAKEOVER = "/evidence/to-take-over",
  EVIDENCE_WAITINGTOTAKEOVER = "/evidence/waiting-to-takeover"
}
